# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8dcdf86c92831bb45f4066393a81fcdf"
name = "geo-bridge"
application_url = "https://www.9shineslabs.com"
embedded = false

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_discounts,read_orders,write_customers,write_discounts"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]
